server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/live_e_commerce?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.springframework.web: DEBUG
    com.live_ecommerce: DEBUG
